### ISSUE TITLE
[Question]: Is it possible to get result from single-value request

### ISSUE THREAD

**Issue by isavitsky** [swoga/mikrotik-exporter#66]
Hello,

I've been struggling for a couple of days now for getting a sensible result from single-value Mikrotik API requests.
For example, this one:
```
/ip/dhcp-server/lease/print
=active=
=count-only=
?server=LAN-8-floor

<<< /ip/dhcp-server/lease/print
<<< =active=
<<< =count-only=
<<< ?server=LAN-8-floor
<<< 
>>> !done
>>> =ret=7
>>>
```
As we can see in this example API returns an unnamed/anonymous object that doesn't fall into `re={…}` response:
```
{ret: 7}
```
In the debug session we see no response to such requests.
The immediate trace reply is:
```
TRC response channel closed
```

My configuration is as follows:
```
modules:
  - name: testx
    commands:
      - command: |-
          /ip/dhcp-server/lease/print
          ?server=LAN-8-floor
          =active=
          =count-only=
        metrics:
          - metric_name: dhcp_entries
            param_name: ret
            param_type: int
            metric_type: gauge
            labels:
              - param_name: source
                param_type: string
                value: dhcp
```
So, is it possible somehow to get this value?
